-- ALTER TABLE "state" DROP CONSTRAINT "fk_state";
-- ALTER TABLE "location" DROP CONSTRAINT "fk_location";
-- ALTER TABLE "address" DROP CONSTRAINT "fk_address";
-- ALTER TABLE "designation_matrix" DROP CONSTRAINT "fk_designation_matrix";
-- ALTER TABLE "designation_matrix" DROP CONSTRAINT "fk_designation_matrix_1";
-- ALTER TABLE "skill_matrix" DROP CONSTRAINT "fk_skill_matrix";
-- ALTER TABLE "skill_matrix" DROP CONSTRAINT "fk_skill_matrix_1";
-- ALTER TABLE "skill_matrix" DROP CONSTRAINT "fk_skill_matrix_3";
-- ALTER TABLE "skill_matrix" DROP CONSTRAINT "fk_skill_matrix_4";
-- ALTER TABLE "roles" DROP CONSTRAINT "fk_roles";
-- ALTER TABLE "account" DROP CONSTRAINT "fk_account";
-- ALTER TABLE "skill_matrix" DROP CONSTRAINT "fk_skill_matrix_2";
--
-- DROP TABLE "state";
-- DROP TABLE "location";
-- DROP TABLE "country";
-- DROP TABLE "employee";
-- DROP TABLE "address";
-- DROP TABLE "skill_matrix";
-- DROP TABLE "skill_category";
-- DROP TABLE "designation_type";
-- DROP TABLE "designation_sub_type";
-- DROP TABLE "designation_matrix";
-- DROP TABLE "skill_name";
-- DROP TABLE "kpi";
-- DROP TABLE "roles";
-- DROP TABLE "account";
-- DROP TABLE "permissions";
-- DROP TABLE "competency";
--
-- CREATE TABLE "state" (
-- "state_id" int NOT NULL,
-- "state_name" varchar(255),
-- "contry_id" int,
-- "city" varchar(100),
-- PRIMARY KEY ("state_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "location" (
-- "location_id" int NOT NULL,
-- "location_name" varchar(255),
-- "state_id" int,
-- "pin" varchar(255),
-- PRIMARY KEY ("location_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "country" (
-- "country_id" int NOT NULL,
-- "contry_name" varchar(255),
-- "contry_desc" varchar(255),
-- PRIMARY KEY ("country_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "employee" (
-- "employee_id" int4 NOT NULL,
-- "name" varchar(255),
-- "email_id" varchar(100),
-- "phone_number" int,
-- "flag" char(255),
-- "gender" varchar(10),
-- "created_by" varchar(100),
-- "creation_date" date,
-- "updated_by" varchar(100),
-- "updated_date" date,
-- PRIMARY KEY ("employee_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "address" (
-- "address_id" int NOT NULL,
-- "land_mark" varchar(255),
-- "city" varchar(255),
-- "state" varchar(255),
-- "country" varchar(255),
-- "employee_id" int,
-- "address2" varchar(100),
-- "area" varchar(100),
-- "pincode" int,
-- PRIMARY KEY ("address_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "skill_matrix" (
-- "skill_matrix_id" int NOT NULL,
-- "skill_category_id" int,
-- "designation_id" int,
-- "employee_id" int,
-- "skill_id" int,
-- "no_of_years" varchar(255),
-- "isCertified" varchar(255),
-- "name_of_institute" varchar(255),
-- "score" varchar(255),
-- "kpi_id" int,
-- "no_of_moths" varchar(255),
-- PRIMARY KEY ("skill_matrix_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "skill_category" (
-- "id" int NOT NULL,
-- "skill_category_name" varchar(255),
-- "skill_category_description" varchar(255),
-- PRIMARY KEY ("id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "designation_type" (
-- "id" int NOT NULL,
-- "designation_name" varchar(255),
-- "desig_description" varchar(255),
-- PRIMARY KEY ("id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "designation_sub_type" (
-- "id" int NOT NULL,
-- "sub_type_name" varchar(100),
-- "dest_type_description" varchar(100),
-- PRIMARY KEY ("id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "designation_matrix" (
-- "id" int4 NOT NULL,
-- "disgnation_type_id" int4,
-- "disgnation_sub_id" int4,
-- PRIMARY KEY ("id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "skill_name" (
-- "skill_id" int4 NOT NULL,
-- "skill_name" varchar(255),
-- "skill_desc" varchar(255),
-- PRIMARY KEY ("skill_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "kpi" (
-- "id" int NOT NULL,
-- "employee_target" varchar(255),
-- "rechead_target" varchar(255),
-- "comments" varchar(255),
-- PRIMARY KEY ("id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "roles" (
-- "role_id" int NOT NULL,
-- "role_name" varchar(255),
-- "permisson_Id" int,
-- "role_description" varchar(255),
-- PRIMARY KEY ("role_id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "account" (
-- "id" int NOT NULL,
-- "employee_id" int,
-- "role_id" int,
-- "password" varchar(100),
-- "user_id" varchar(100),
-- PRIMARY KEY ("id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "permissions" (
-- "id" int NOT NULL,
-- "permissition_name" varchar(255),
-- "permission_description" varchar(255),
-- PRIMARY KEY ("id")
-- )
-- WITHOUT OIDS;
-- CREATE TABLE "competency" (
-- "c_id" int NOT NULL,
-- "competency_skill" varchar(255),
-- "competency_desc" varchar(255),
-- "created_date" date,
-- PRIMARY KEY ("c_id")
-- )
-- WITHOUT OIDS;
--
-- ALTER TABLE "state" ADD CONSTRAINT "fk_state" FOREIGN KEY ("contry_id") REFERENCES "country" () ON DELETE CASCADE ON UPDATE NO ACTION;
-- ALTER TABLE "location" ADD CONSTRAINT "fk_location" FOREIGN KEY ("state_id") REFERENCES "state" () ON DELETE CASCADE ON UPDATE NO ACTION;
-- ALTER TABLE "address" ADD CONSTRAINT "fk_address" FOREIGN KEY ("employee_id") REFERENCES "employee" ();
-- ALTER TABLE "designation_matrix" ADD CONSTRAINT "fk_designation_matrix" FOREIGN KEY ("disgnation_type_id") REFERENCES "designation_type" () ON DELETE CASCADE;
-- ALTER TABLE "designation_matrix" ADD CONSTRAINT "fk_designation_matrix_1" FOREIGN KEY ("disgnation_sub_id") REFERENCES "designation_sub_type" () ON DELETE CASCADE;
-- ALTER TABLE "skill_matrix" ADD CONSTRAINT "fk_skill_matrix" FOREIGN KEY ("employee_id") REFERENCES "employee" ();
-- ALTER TABLE "skill_matrix" ADD CONSTRAINT "fk_skill_matrix_1" FOREIGN KEY ("designation_id") REFERENCES "designation_matrix" ();
-- ALTER TABLE "skill_matrix" ADD CONSTRAINT "fk_skill_matrix_3" FOREIGN KEY ("skill_id") REFERENCES "skill_name";
-- ALTER TABLE "skill_matrix" ADD CONSTRAINT "fk_skill_matrix_4" FOREIGN KEY ("kpi_id") REFERENCES "kpi" ;
-- ALTER TABLE "roles" ADD CONSTRAINT "fk_roles" FOREIGN KEY ("permisson_Id") REFERENCES "permissions" ;
-- ALTER TABLE "account" ADD CONSTRAINT "fk_account" FOREIGN KEY ("role_id") REFERENCES "roles" ;
-- ALTER TABLE "skill_matrix" ADD CONSTRAINT "fk_skill_matrix_2" FOREIGN KEY ("skill_category_id") REFERENCES "skill_category";
--
